name: D:\CS\projects\nlp-image-captioning\.conda
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - abseil-cpp=20210324.2=hd77b12b_0
  - aiohttp=3.8.3=py39h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - astor=0.8.1=py39haa95532_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py39haa95532_0
  - attrs=22.1.0=py39haa95532_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blinker=1.4=py39haa95532_0
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2023.01.10=haa95532_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.12.7=py39haa95532_0
  - cffi=1.15.1=py39h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39haa95532_0
  - colorama=0.4.6=py39haa95532_0
  - cryptography=38.0.4=py39h21b164f_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - cudnn=8.2.1=cuda11.3_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fftw=3.3.9=h2bbff1b_1
  - flatbuffers=2.0.0=h6c2663c_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.3.3=py39h2bbff1b_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h8cc25b3_1
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.42.0=py39hc60d5dd_0
  - h5py=3.7.0=py39h3de5c98_0
  - hdf5=1.10.6=h1756f20_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=68.1=h6c2663c_0
  - idna=3.4=py39haa95532_0
  - importlib-metadata=4.11.3=py39haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.15.0=pyh025b116_0
  - ipython=8.10.0=pyh08f2357_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - joblib=1.1.1=py39haa95532_0
  - jpeg=9e=h2bbff1b_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py39hcbf5309_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - lerc=3.0=hd77b12b_0
  - libcurl=7.87.0=h86230a5_0
  - libdeflate=1.8=h2bbff1b_5
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.17.2=h23ce68f_1
  - libsodium=1.0.18=h8d14728_1
  - libssh2=1.10.0=hcd4344a_0
  - libtiff=4.5.0=h6c2663c_1
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - lz4-c=1.9.4=h2bbff1b_0
  - markdown=3.4.1=py39haa95532_0
  - markupsafe=2.1.1=py39h2bbff1b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - multidict=6.0.2=py39h2bbff1b_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nltk=3.7=pyhd3eb1b0_0
  - numpy=1.23.5=py39h3b20f71_0
  - numpy-base=1.23.5=py39h4da318b_0
  - oauthlib=3.2.1=py39haa95532_0
  - openssl=1.1.1s=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=22.0=py39haa95532_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.3.0=py39hd77b12b_2
  - pip=22.3.1=py39haa95532_0
  - platformdirs=2.5.2=py39haa95532_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.0=py39h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyjwt=2.4.0=py39haa95532_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.16=h6244533_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-flatbuffers=1.12=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pywin32=227=py39hb82d6ee_1
  - pyzmq=23.2.0=py39hd77b12b_0
  - regex=2022.7.9=py39h2bbff1b_0
  - requests=2.28.1=py39haa95532_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - ruamel.yaml=0.17.21=py39h2bbff1b_0
  - ruamel.yaml.clib=0.2.6=py39h2bbff1b_1
  - scikit-learn=1.2.0=py39hd77b12b_0
  - scipy=1.10.0=py39h321e85e_0
  - setuptools=65.6.3=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h6c2663c_0
  - sqlite=3.40.1=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py39haa95532_0
  - tensorboard-plugin-wit=1.8.1=py39haa95532_0
  - tensorflow-gpu=2.6.0=h17022bd_0
  - termcolor=2.1.0=py39haa95532_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.2=py39hb82d6ee_0
  - tqdm=4.64.1=py39haa95532_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing_extensions=4.4.0=py39haa95532_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.14=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - werkzeug=2.2.2=py39haa95532_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - wrapt=1.14.1=py39h2bbff1b_0
  - xz=5.2.10=h8cc25b3_1
  - yarl=1.8.1=py39h2bbff1b_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.11.0=py39haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
      - absl-py==1.4.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - fonttools==4.39.2
      - importlib-resources==5.12.0
      - keras==2.10.0
      - keras-self-attention==0.51.0
      - kiwisolver==1.4.4
      - libclang==16.0.0
      - matplotlib==3.7.1
      - protobuf==3.19.6
      - pyparsing==3.0.9
      - tensorboard==2.10.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-hub==0.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - torch==1.13.1+cu116
      - torchaudio==0.13.1+cu116
      - torchvision==0.14.1+cu116
prefix: D:\CS\projects\nlp-image-captioning\.conda
